import {
  HiOutlineCamera,
  HiOutlineVideoCamera,
  HiOutlineCodeBracket,
  HiOutlineChartBar,
  HiOutlineSun,
  HiOutlineMoon,
  HiOutlineSparkles,
  HiOutlineCloud,
  HiOutlineHome,
  HiOutlineUser,
  HiOutlineGlobeAlt,
  HiOutlineClock,
  HiOutlineShieldCheck,
  HiOutlineEye,
  HiOutlineRocketLaunch,
  HiOutlineMagnifyingGlass,
  HiOutlinePencilSquare,
  HiOutlineSquare3Stack3D,
  HiOutlineBolt,
  HiOutlineCheckBadge,
  HiOutlineArrowRight,
  HiOutlineArrowUpRight,
  HiOutlinePlay,
  HiOutlineStar,
  HiOutlineEnvelope,
  HiOutlinePhone,
  HiOutlineMapPin,
  HiOutlineChevronDown,
  HiOutlineXMark,
  HiOutlineBars3,
  HiOutlineHeart,
  HiOutlineFaceSmile,
  HiOutlineFilm,
  HiOutlinePhoto,
} from 'react-icons/hi2';
import {
  SiGoogle,
  SiMeta,
} from 'react-icons/si';
import {
  FaGem,
  FaCouch,
  FaBriefcase,
  FaMobileScreen,
  FaDroplet,
  FaBullhorn,
  FaBullseye,
  FaStar,
  FaFileLines,
  FaShareNodes,
  FaRobot,
} from 'react-icons/fa6';

const MAP = {
  photo: HiOutlineCamera,
  video: HiOutlineVideoCamera,
  code: HiOutlineCodeBracket,
  growth: HiOutlineChartBar,
  sun: HiOutlineSun,
  moon: HiOutlineMoon,
  eraser: HiOutlineSparkles,
  cloud: HiOutlineCloud,
  sofa: FaCouch,
  home: HiOutlineHome,
  gem: FaGem,
  face: HiOutlineUser,
  sparkles: HiOutlineSparkles,
  briefcase: FaBriefcase,
  heart: HiOutlineHeart,
  phone: FaMobileScreen,
  droplet: FaDroplet,
  play: HiOutlinePlay,
  megaphone: FaBullhorn,
  globe: HiOutlineGlobeAlt,
  mobile: FaMobileScreen,
  cube: HiOutlineSquare3Stack3D,
  robot: FaRobot,
  pen: HiOutlinePencilSquare,
  search: HiOutlineMagnifyingGlass,
  target: FaBullseye,
  google: SiGoogle,
  star: FaStar,
  share: FaShareNodes,
  doc: FaFileLines,
  clock: HiOutlineClock,
  shield: HiOutlineShieldCheck,
  eye: HiOutlineEye,
  rocket: HiOutlineRocketLaunch,
  bolt: HiOutlineBolt,
  medal: HiOutlineCheckBadge,
  strategy: FaBullseye,
  arrowRight: HiOutlineArrowRight,
  arrowUpRight: HiOutlineArrowUpRight,
  film: HiOutlineFilm,
  image: HiOutlinePhoto,
  smile: HiOutlineFaceSmile,
  envelope: HiOutlineEnvelope,
  phoneIcon: HiOutlinePhone,
  map: HiOutlineMapPin,
  chevronDown: HiOutlineChevronDown,
  close: HiOutlineXMark,
  menu: HiOutlineBars3,
};

export default function Icon({ name, className = 'w-5 h-5' }) {
  const Cmp = MAP[name] || HiOutlineSparkles;
  return <Cmp className={className} aria-hidden="true" />;
}
